### ISSUE TITLE
使用pip安装完之后 运行repoagent configure 报错

### ISSUE THREAD

**Issue by zkandroid** [OpenBMB/RepoAgent#64]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/repoagent", line 5, in <module>
    from repo_agent.main import app
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/repo_agent/main.py", line 28, in <module>
    repo_path: Annotated[str, typer.Option(prompt="Enter the path to your local repository")] = settings.repo_path ,
                                                                                                ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dynaconf/base.py", line 145, in __getattr__
    value = getattr(self._wrapped, name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dynaconf/base.py", line 328, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'REPO_PATH'

**Comment by Umpire2018** [comment]
<img width="564" alt="image" src="https://github.com/OpenBMB/RepoAgent/assets/138990495/d324471f-e0d4-4c75-8f28-ff75ab005ac2">

您好，我无法复现您遇到的问题。请提供更多信息如使用版本，系统供参考。
