### ISSUE TITLE
win 11  repoagent configure 失败

### ISSUE THREAD

**Issue by ShaneDean** [OpenBMB/RepoAgent#65]
报错信息
```
(venv) PS C:\git\RepoAgent> repoagent configure
C:\git\RepoAgent\venv\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\git\RepoAgent\venv\Scripts\repoagent.exe\__main__.py", line 4, in <module>
  File "C:\git\RepoAgent\repo_agent\main.py", line 12, in <module>
    from repo_agent.chat_with_repo import main as run_chat_with_repo
  File "C:\git\RepoAgent\repo_agent\chat_with_repo\__init__.py", line 3, in <module>
    from .main import main
  File "C:\git\RepoAgent\repo_agent\chat_with_repo\main.py", line 3, in <module>
    from repo_agent.settings import setting
  File "C:\git\RepoAgent\repo_agent\settings.py", line 87, in <module>
    setting = Setting.model_validate(_config_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\RepoAgent\venv\Lib\site-packages\pydantic\main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Setting
chat_completion.openai_api_key
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
```

查了下已经修复了但是没有release

https://github.com/microsoft/onnxruntime/commit/7b46b3155891cbf6c783e2535e413b92ae81b050

**Comment by LOGIC-10** [comment]
@Umpire2018

**Comment by Umpire2018** [comment]
@ShaneDean 您好，多谢告知。此提示中存在两个问题。
1. UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only. 今日修复。
2. pydantic_core._pydantic_core.ValidationError: 1 validation error for Setting chat_completion.openai_api_key 此为提示环境变量没有被设置。
