### ISSUE TITLE
cannot run or configure the repoagent, anyone facing similar issues?

### ISSUE THREAD

**Issue by kaijunhan** [OpenBMB/RepoAgent#75]
Tried this on both windows and macos, got the same error 

Traceback (most recent call last):
  File "/Users/XXX/Library/Python/3.9/bin/repoagent", line 5, in <module>
    from repo_agent.main import app
  File "/Users/XXX/Library/Python/3.9/lib/python/site-packages/repo_agent/main.py", line 28, in <module>
    repo_path: Annotated[str, typer.Option(prompt="Enter the path to your local repository")] = settings.repo_path ,
  File "/Users/XXX/Library/Python/3.9/lib/python/site-packages/dynaconf/base.py", line 145, in __getattr__
    value = getattr(self._wrapped, name)
  File "/Users/XXX/Library/Python/3.9/lib/python/site-packages/dynaconf/base.py", line 328, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Settings' object has no attribute 'REPO_PATH'

**Comment by Umpire2018** [comment]
I wonder what version you are using? I can not reproduce your error.

Besides, we are using `target_repo_path` in `repo_agent/main.py.

https://github.com/OpenBMB/RepoAgent/blob/e559bf1a4b12734f1bac69dbdf943d3a37490604/repo_agent/main.py#L65-L76

**Comment by bharatnpti** [comment]
i faced this issues with repoagent 0.0.5. updated your python version and then install repoagent - this will install the latest version of repoagent
