### ISSUE TITLE
repoagent configure | not working

### ISSUE THREAD

**Issue by bharatnpti** [OpenBMB/RepoAgent#77]
_Python 3.12.6
repoagent 0.1.3_

**repoagent configure**
```
Traceback (most recent call last):eDocumentation % repoagent configure 
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/bin/repoagent", line 5, in <module>
    from repo_agent.main import cli
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/repo_agent/main.py", line 12, in <module>
    from repo_agent.chat_with_repo import main as run_chat_with_repo
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/repo_agent/chat_with_repo/__init__.py", line 3, in <module>
    from .main import main
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/repo_agent/chat_with_repo/main.py", line 3, in <module>
    from repo_agent.settings import setting
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/repo_agent/settings.py", line 27, in <module>
    class ProjectSettings(BaseSettings):
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__
    complete_model_class(
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_model_construction.py", line 573, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/main.py", line 668, in __get_pydantic_core_schema__
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1332, in _common_field_schema
    schema = self._apply_field_serializers(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 2221, in _apply_field_serializers
    is_field_serializer, info_arg = inspect_field_serializer(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bharatbhushan/PycharmProjects/LLMCodeDocumentation/LLMCodeDocumentation/env1/lib/python3.12/site-packages/pydantic/_internal/_decorators.py", line 586, in inspect_field_serializer
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Unrecognized field_serializer function signature for <function ProjectSettings.serialize_ignore_list at 0x17efbd080> with `mode=plain`:(self, ignore_list: list[str] = [])

For further information visit https://errors.pydantic.dev/2.9/u/field-serializer-signature
```

**Comment by Asif-droid** [comment]
facing this error in configure:
 repoagent configure
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\Scripts\repoagent.exe\__main__.py", line 4, in <module>
    from repo_agent.main import cli
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\repo_agent\main.py", line 12, in <module>
    from repo_agent.chat_with_repo import main as run_chat_with_repo
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\repo_agent\chat_with_repo\__init__.py", line 3, in <module>
    from .main import main
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\repo_agent\chat_with_repo\main.py", line 3, in <module>
    from repo_agent.settings import setting
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\repo_agent\settings.py", line 1, in <module>
    from enum import StrEnum
ImportError: cannot import name 'StrEnum' from 'enum' (C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\enum.py)
